### ISSUE TITLE
Can't see or click last tab on Windows 7

### ISSUE THREAD

**Issue by mikeconley** [bwinton/VerticalTabs#284]
Using Tab Center 1.18, I have enough tabs open that I can scroll them.

I've gotten into a state where if I open a new tab, and it gets appended to the end of the tab strip, I cannot access it easily. I can see a few of its top-most pixels, but I definitely can't see the tab title.

Here's a screenshot:

![pin](https://cloud.githubusercontent.com/assets/195042/15543648/b4396f80-2263-11e6-80de-ab1c837b67e4.png)

There's a tab under that "Live Weekly" Reddit tab that I'm hovering, but the Windows 7 task bar is in the way.

**Comment by Keith94** [comment]
Same here. I applied css for a temporary fix...

```css
#verticaltabs-box .tabbrowser-arrowscrollbox {
  padding-bottom: 36px !important;
}
```

May be dupe of #238.
