### ISSUE TITLE
Add ESLint linting?

### ISSUE THREAD

**Issue by pdehaan** [bwinton/VerticalTabs#63]
Not sure if we want to add some basic ESLint linting to detect any potential errors or issues.
Should be simple enough to add linting directly in Travis-CI pipeline so the repo doesn't have any Node.js dependencies or whatever.

```bash
$ eslint --version
v2.8.0

$ eslint .

/Users/pdehaan/dev/github/VerticalTabs/bootstrap.js
   39:17  error    'Cc' is defined but never used         no-unused-vars
   58:7   error    'branch' is defined but never used     no-unused-vars
   76:19  error    'value' is defined but never used      no-unused-vars
   81:10  error    'install' is defined but never used    no-unused-vars
   84:10  error    'startup' is defined but never used    no-unused-vars
  100:3   error    'watchWindows' is not defined          no-undef
  104:2   error    Unnecessary semicolon                  no-extra-semi
  106:10  error    'shutdown' is defined but never used   no-unused-vars
  107:14  warning  Expected '===' and instead saw '=='    eqeqeq
  114:10  error    'uninstall' is defined but never used  no-unused-vars

/Users/pdehaan/dev/github/VerticalTabs/utils.js
   58:17  warning  Expected '===' and instead saw '=='       eqeqeq
   62:16  warning  Expected '===' and instead saw '=='       eqeqeq
   71:17  warning  Expected '!==' and instead saw '!='       eqeqeq
   89:7   warning  Unexpected console statement              no-console
   97:15  warning  Expected '!==' and instead saw '!='       eqeqeq
  109:10  error    'watchWindows' is defined but never used  no-unused-vars
  115:54  warning  Expected '===' and instead saw '=='       eqeqeq
  119:7   warning  Unexpected console statement              no-console
  137:36  warning  Expected '===' and instead saw '=='       eqeqeq
  146:15  warning  Expected '===' and instead saw '=='       eqeqeq

✖ 20 problems (10 errors, 10 warnings)
```

And my crude .eslintrc file looks like:
```yaml
extends: eslint:recommended

env:
  browser: true
  es6: true

globals:
  APP_SHUTDOWN: false
  Components: false
  Iterator: false
  Services: false
  VerticalTabs: false
  shutdown: false
  unload: false

rules:
  eqeqeq: 1
  no-console: 1
  no-unused-vars: [2, {vars: all, args: none}]
```
